### PR TITLE
File validations

### PR DESCRIPTION
**Pull request by mtakac**
Okay so I changed the `collectFormValues` function. It now returns `File` object for file input and `FileList`  if the attribute `multiple` is set on the input. I didn't find any tests for `collectFormValues` maybe @ansman could point me to some? Or maybe we don't need to test the function and I'll add some test for file validators?

I was thinking about the API for the file validator(s). In the first round it should support at least file size (min & max) and file type validations (can you think of some other?). 

I see two possible aproaches:

**Create one file validator and allow user to specify allowed file sizes and types in the options. Something like this:**
```
validate({attachment: File}, {attachment: {file: {minSize: 1000, maxSize: 20000, types: ['image/*', application/zip]}}});
```

**Create separate validator for each property**
- Size:
```
validate({attachment: File}, {attachment: {size: {min: 1000, max: 20000}}});
```
- Type:
```
validate({attachment: File}, {attachment: {types: {{allow: ['image/*']}});
```

I think the most common use case is white listing the allowed types, but we can also add black listing (e.g. allow everything aprat from black-listed).

Personally I prefer the first option. Or of course we can just leave it up to the user to create his own custom file validations.

### CODE REVIEW

**Comment by ansman** [comment]
That was quick!

The tests for `collectFormValues` are in [`specs/validate-helpers-spec.js`](https://github.com/ansman/validate.js/blob/master/specs/validate-helpers-spec.js#L817)

I too prefer the first option, the meaning of `size` and `types` becomes ambiguous if used outside of the validator scope so it's better to encapsulate them as options like you suggested.

Thanks

**Comment by Abijeet** [comment]
@ansman - When are you planning to merge this, 1.0 ?

**Comment by ansman** [comment]
@Abijeet I'm still waiting for some tests to be added to the PR.

**Comment by ansman** [comment]
I'm closing this due to inactivity, let me know if anything changes.

**Pull request closed without merging**
