### PR TITLE
Fix #2: add support for custom validators

### LINKED ISSUE #2: Support custom validators in the constraints schema
This would be useful for when you want a validator to be used in just a special case.

The format could be:

``` javascript
{
  "<attribute>": {
    "<validator name>": function(value, options, key, attributes) {
      ...
    }
  }
}
```

### PR DESCRIPTION
**Pull request by toddmazierski**
Allow for ad-hoc validators to be defined directly in the constraints schema.

Thanks for considering this contribution!

### CODE REVIEW

**Comment by ansman** [comment]
Sweet, thanks for implementing this.

Should we also do anything about the result? With your implementation the `validator` key in the detailed error format will be the function. Perhaps that is what we want.

**Comment by toddmazierski** [comment]
@ansman, you're welcome! Thanks for taking a look.

To facilitate discussion, I wrote a test (f861ec5) for the `"detailed"` format. The value for the `validator` key _seems_ to be set as expected (`"someCustomValidator"`)—but the value for the `options` key does seem strange: it looks like it's the _result_ of the custom validator function (`"some error message"`).

What do you think would be the expected behavior for `options` in the case of custom validators? Perhaps it should be set to `undefined` or `{}`, or not included at all?

**Comment by toddmazierski** [comment]
Hi, @ansman! Any thoughts on my [previous comment](https://github.com/ansman/validate.js/pull/135#issuecomment-229364610)? Thanks!

**Comment by ansman** [comment]
Sorry, I've been on vacation.

Ah, I see, in that case that's fine.

The reason your options ends up being wrong is because the options can be a function to allow dynamic options. The best solution would be to set the `validatorOptions` to be `undefined` if the validator is inlined.

**Comment by toddmazierski** [comment]
Doing some spring cleaning and closing this. I'm no longer a user of validate.js so I'm less motivated to follow through on this change. My apologies for any inconvenience. Anyone is free to pick this up, of course, if they'd like.

**Pull request closed without merging**
